StackQueues.StackList linkedListStack = new StackQueues.StackList();
linkedListStack.push(70);
linkedListStack.push(30);
linkedListStack.push(56);
linkedListStack.Display();
linkedListStack.peek();
linkedListStack.Display();
linkedListStack.pop();
linkedListStack.Display();
linkedListStack.isEmpty();
linkedListStack.Display();
StackQueues.QueueList queueList = new StackQueues.QueueList();
queueList.Enqueue(56);
queueList.Enqueue(30);
queueList.Enqueue(70);
queueList.Display();