StackQueues.StackList linkedListStack = new StackQueues.StackList();
linkedListStack.push(70);
linkedListStack.push(30);
linkedListStack.push(56);
linkedListStack.Display();
linkedListStack.peek();
linkedListStack.Display();
linkedListStack.pop();
linkedListStack.Display();
linkedListStack.isEmpty();
linkedListStack.Display();